all:
  vars:
    ansible_user: devops
    ansible_ssh_private_key_file: ~/.ssh/id_devops

  children:

    vms:
      children:

        ci:
          hosts:
            ci-01:
              ansible_host: 192.168.56.11

        k8s_master:
          hosts:
            k8s-master:
              ansible_host: 192.168.56.21

        k8s_workers:
          hosts:
            k8s-worker1:
              ansible_host: 192.168.56.22
              zone: host

            k8s-worker2:
              ansible_host: 192.168.56.23
              zone: host

            k8s-worker3:
              ansible_host: 192.168.56.24
              zone: laptop

        db:
          hosts:
            db-01:
              ansible_host: 192.168.56.31

        monitoring:
          hosts:
            mon-01:
              ansible_host: 192.168.56.41

    machines:
      hosts:

        devops-server:
          ansible_connection: local

        laptop-01:
          ansible_host: 192.168.56.2
