- name: Reload ssh
  ansible.builtin.service:
    name: ssh
    state: reloaded

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart node_exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: restarted

- name: Validate netplan
  ansible.builtin.command: netplan generate
  changed_when: false
